"""add action column to ui_locator_cache

Revision ID: 03cb3994f22a
Revises: eb87d2e87634
Create Date: 2025-08-30 19:17:32.786962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03cb3994f22a'
down_revision: Union[str, Sequence[str], None] = 'eb87d2e87634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ui_locator_cache', sa.Column('action', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ui_locator_cache', 'action')
    # ### end Alembic commands ###
