"""update project id in cache table

Revision ID: 6975441017a7
Revises: 
Create Date: 2025-08-05 20:55:51.861803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6975441017a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'project_invites', 'users', ['invited_by_user_id'], ['id'])
    op.create_foreign_key(None, 'project_invites', 'users', ['invited_user_id'], ['id'])
    op.create_foreign_key(None, 'project_memberships', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.alter_column('ui_locator_cache', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ui_locator_cache', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'project_memberships', type_='foreignkey')
    op.drop_constraint(None, 'project_invites', type_='foreignkey')
    op.drop_constraint(None, 'project_invites', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    # ### end Alembic commands ###
