"""update project id in api usage table

Revision ID: eb87d2e87634
Revises: 6975441017a7
Create Date: 2025-08-05 21:59:05.679593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb87d2e87634'
down_revision: Union[str, Sequence[str], None] = '6975441017a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_usage', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('api_usage', 'api_key_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_usage', 'api_key_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('api_usage', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
