
name: Sanity Test

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'CONTRIBUTING.md'
      - '.gitignore'
      - '**/*.md'

jobs:
  black:
      name: test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"
            cache: "pip"
        - name: Install Poetry
          run: |
            pip install poetry
        - name: Install Dependencies
          run: |
            poetry install --with dev --no-ansi
        - name: Lint Checks
          run: |
            poetry run ruff check ./talk2dom
            poetry run ruff format --check ./talk2dom
        - name: Run Unittest
          run: |
            export PYTHONPATH=$(pwd)
            poetry run pytest tests